version: "3.1"
services:
  memcached:
    image: memcached:alpine
    container_name: yii2-bootstrap4-memcached

  mysql:
    build: docker/mysql
    container_name: yii2-bootstrap4-mysql
    working_dir: /application
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./runtime/mysql:/var/log/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  webserver:
    build: docker/nginx
    container_name: yii2-bootstrap4-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
      - memcached

  php-fpm:
    build: docker/php-fpm
    container_name: yii2-bootstrap4-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
  composer:
    build:
      context: ./docker/composer
    volumes:
      - ${DOCUMENT_ROOT-./}:/application
    working_dir: /application
    #command: install --ignore-platform-reqs --prefer-dist
  nodejs:
    build:
      context: ./docker/nodejs
    volumes:
      - .:/application
    working_dir: /application
    #command: npm i
